### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by arturosinski** [johnzuk/GusApi#20]
In exampel U use file : ../vendor/autoload.php ? 
Can't find it in the project.
Also U can't run stand alone file/examples/getFromNip.php, error : 
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in examples/getFromNip.php on line 6

I have also problems with the namespace, but upgrade php version up 5.3 help.
Now i require_onece files, but have another problem:
Parse error: syntax error, unexpected '[' in /GusApi/GusApi.php on line 145

The praser can't prase corect, line:
public function getByNip($sid, $nip)
    {
        return $this->search($sid, [
            RegonConstantsInterface::SEARCH_TYPE_NIP => $nip
        ]);
    }
Can U let me knew where is the problem ?

**Comment by johnzuk** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Hi you need to install composer first, https://getcomposer.org/doc/00-intro.md and next run composer install in main directory. Please notice that you should use php >= 5.3
Dnia Niedziela, 23 Kwietnia 2017 08:26 arturosinski <notifications@github.com> napisał(a)

I exampel U use file : ../vendor/autoload.php ? Can't find it in the project. Also u can;t run stand alone file/examples/getFromNip.php, error : Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in examples/getFromNip.php on line 6
—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/johnzuk/GusApi","title":"johnzuk/GusApi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/johnzuk/GusApi"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Can't find file (#20)"}],"action":{"name":"View Issue","url":"https://github.com/johnzuk/GusApi/issues/20"}}}
// ]]>


Pozdrawiam,
Janusz Żukowicz

**Comment by arturosinski** [comment]
Ok Thanks. 
I dont knew nothing about https://getcomposer.org/doc/00-intro.md, i read it and don't understand a thing. :) 
Im using hosting from home.pl so no console etc. 
But for now i just simple require_once all neccessary files when i get error and update version php to 5,4 .
And it work's now. (i have to also add to GusApi.php , GusApi/SearchReport , becouse i get Fatal error not having class)
Thanks
